source 'http://rubygems.org'

gem 'aws-sdk'
gem 'sinatra'
gem 'json'
gem 'rack'
gem 'rack-contrib'
gem 'dynamoid'
gem 'rake'
gem 'rubysl-base64'


# These are the dependencies that are used only for unit tests.
group :test do
  gem "rspec"
  gem "rack-test"
end